version: '3.3'

services:
  db:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
  app:
    depends_on:
      - db
    image: docker pull ghcr.io/viyika/re-commerce-api:030920232111
    ports:
      - "8080:80"
    restart: always
    environment:
      DB_HOST: db:3306
      DB_USER: wordpress
      DB_PASSWORD: wordpress
volumes:
  db_data: