version: '3.3'

services:
  db:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
  app:
    depends_on:
      - db
    image: ghcr.io/viyika/re-commerce-api:040920232048
    ports:
      - "8080:8080"
    restart: always
    environment:
      DB_URI: mongodb://db:27017/mydatabase
      DB_USERNAME: root
      DB_PASSWORD: secret
volumes:
  db_data:
